package com.ncdc.nise.utils

class Constants {
    companion object {
        const val CITY = "city"
        const val STATE = "state"
        const val UserId="userId"
        const val UserName="username"
        const val SurveyId="surveyId"
        const val editSurveyId="editSurveyId"
        const val isEdit="isEdit"
        const val isBackPressed="isBack"
        const val isLogin="isLogin"
      /*  var statesArray = arrayOf(
            "Select State",
            "Andaman and Nicobar Islands",
            "Andhra Pradesh",
            "Arunachal Pradesh",
            "Assam",
            "Bihar",
            "Chandigarh",
            "Chhattisgarh",
            "Dadra Nagar Haveli",
            "Daman Diu",
            "Delhi",
            "Goa",
            "Gujarat",
            "Haryana",
            "Himachal Pradesh",
            "Jammu & Kashmir",
            "Jharkhand",
            "Karnataka",
            "Kerala",
            "Ladakh",
            "Lakshadweep",
            "Madhya Pradesh",
            "Maharashtra",
            "Manipur",
            "Meghalaya",
            "Mizoram",
            "Nagaland",
            "Odisha",
            "Puducherry",
            "Punjab",
            "Rajasthan",
            "Sikkim",
            "Tamil Nadu",
            "Telangana",
            "Tripura",
            "Uttarakhand",
            "Uttar Pradesh",
            "West Bengal"
        )*/


        var statesArray = arrayOf(
            "Select State",
            "JAMMU and KASHMIR",
            "HIMACHAL PRADESH",
            "PUNJAB",
            "CHANDIGARH",
            "UTTARAKHAND",
            "HARYANA",
            "DELHI",
            "RAJASTHAN",
            "UTTAR PRADESH",
            "BIHAR",
            "SIKKIM",
            "ARUNACHAL PRADESH",
            "NAGALAND",
            "MANIPUR",
            "MIZORAM",
            "TRIPURA",
            "MEGHALAYA",
            "ASSAM",
            "WEST BENGAL",
            "JHARKHAND",
            "ORISSA",
            "CHHATTISGARH",
            "MADHYA PRADESH",
            "GUJARAT",
            "DAMAN and DIU",
            "DADRA and NAGAR HAVELI",
            "MAHARASHTRA",
            "ANDHRA PRADESH",
            "KARNATAKA",
            "GOA",
            "LAKSHADWEEP",
            "KERALA",
            "TAMIL NADU",
            "PUDUCHERRY",
            "ANDAMAN and NICOBAR ISLANDS",
            "TELANGANA",
            "Ladakh UT"
        )


        fun getIndexOf(state: String?): Int {
            for (i in statesArray.indices) {
                if (statesArray.get(i) == state) {
                    return i
                }
            }
            return 0
        }

        fun getIndexOf(city: String?, pos: Int): Int {
            val arr = districtsArray[pos]
            for (i in arr.indices) {
                if (arr[i] == city) {
                    return i
                }
            }
            return 0
        }

        var districtsArray = arrayOf(
            arrayOf(
                "Select District"
            ), arrayOf(
                "Select District",
                "Kupwara",
                "North And Middle Andaman",
                "Badgam",
                "Leh (Ladakh)",
                "Kargil",
                "Poonch",
                "Rajauri",
                "Kathua",
                "Baramula",
                "Bandipore",
                "Srinagar",
                "Ganderbal",
                "Pulwama",
                "Shopian",
                "Anantnag",
                "Kulgam",
                "Doda",
                "Ramban",
                "Kishtwar",
                "Udhampur",
                "Reasi",
                "Jammu",
                "Samba"
            ), arrayOf(
                "Select District",
                "Chamba",
                "Kangra",
                "Lahul & Spiti",
                "Kullu",
                "Mandi",
                "Hamirpur",
                "Una",
                "Bilaspur",
                "Solan",
                "Sirmaur",
                "Shimla",
                "Kinnaur"
            ), arrayOf(
                "Select District",
                "Gurdaspur",
                "Kapurthala",
                "Jalandhar",
                "Hoshiarpur",
                "Shri Muktsar sahib",
                "Fatehgarh Sahib",
                "Ludhiana",
                "Moga",
                "Firozpur",
                "Pathankot",
                "Faridkot",
                "Bathinda",
                "Mansa",
                "Patiala",
                "Amritsar",
                "Tarn Taran",
                "Rup Nagar",
                "S A S Nagar",
                "Sangrur",
                "Barnala"
            ),arrayOf(
                "Select District",
                "Chandigarh"
            ),arrayOf(
                "Select District",
                "Uttarkashi",
                "Chamoli",
                "Rudraprayag",
                "Tehri Garhwal",
                "Dehradun",
                "Pauri Garhwal",
                "Pithoragarh",
                "Bageshwar",
                "Almora",
                "Champawat",
                "Nainital",
                "Udham Singh Nagar",
                "Haridwar"
            ), arrayOf(
                "Select District",
                "Panchkula",
                "Ambala",
                "Yamunanagar",
                "Kurukshetra",
                "Kaithal",
                "Karnal",
                "Panipat",
                "Sonipat",
                "Jind",
                "Fatehabad",
                "Sirsa",
                "Hisar",
                "Bhiwani",
                "Rohtak",
                "Jhajjar",
                "Mahendragarh",
                "Rewari",
                "Gurugram",
                "Mewat",
                "Faridabad",
                "Palwal",
                "Charkhi Dadri"
            ), arrayOf(
                "Select District",
                "North West Delhi",
                "North Delhi",
                "North East Delhi",
                "East Delhi",
                "New Delhi",
                "Central Delhi",
                "West Delhi",
                "South West Delhi",
                "South Delhi",
                "Shahdara",
                "South East Delhi"
            ),
            arrayOf(
                "Select District",
                "Sri Ganganagar",
                "Hanumangarh",
                "Bikaner",
                "Churu",
                "Jhunjhunu",
                "Alwar",
                "Bharatpur",
                "Dholpur",
                "Karauli",
                "Sawai Madhopur",
                "Dausa",
                "Jaipur",
                "Sikar",
                "Nagaur",
                "Jodhpur",
                "Jaisalmer",
                "Barmer",
                "Jalore",
                "Sirohi",
                "Pali",
                "Ajmer",
                "Tonk",
                "Bundi",
                "Bhilwara",
                "Rajsamand",
                "Dungarpur",
                "Banswara",
                "Chittorgarh",
                "Kota",
                "Baran",
                "Jhalawar",
                "Udaipur",
                "Pratapgarh"
        ),
              arrayOf(
                  "Select District",
                "Agra",
                "Aligarh",
                "Prayagraj",
                "Ambedkar Nagar",
                "Amethi",
                "Amroha",
                "Auraiya",
                "Azamgarh",
                "Baghpat",
                "Bahraich",
                "Ballia",
                "Balrampur",
                "Banda",
                "Barabanki",
                "Bareilly",
                "Basti",
                "Bhadohi",
                "Bijnor",
                "Budaun",
                "Bulandshahr",
                "Chandauli",
                "Chitrakoot",
                "Deoria",
                "Etah",
                "Etawah",
                "Ayodhya",
                "Farrukhabad",
                "Fatehpur",
                "Firozabad",
                "Gautam Buddha Nagar",
                "Ghaziabad",
                "Ghazipur",
                "Gonda",
                "Gorakhpur",
                "Hamirpur",
                "Hapur",
                "Hardoi",
                "Hathras",
                "Jalaun",
                "Jaunpur",
                "Jhansi",
                "Kannauj",
                "Kanpur Dehat",
                "Kanpur Nagar",
                "Kasganj",
                "Kaushambi",
                "Kushinagar",
                "Kheri",
                "Lalitpur",
                "Lucknow",
                "Maharajganj",
                "Mahoba",
                "Mainpuri",
                "Mathura",
                "Mau",
                "Meerut",
                "Mirzapur",
                "Moradabad",
                "Muzaffarnagar",
                "Pilibhit",
                "Pratapgarh",
                "RaeBareli",
                "Rampur",
                  "Saharanpur",
                "Sambhal",
                "Sant Kabir Nagar",
                "Shahjahanpur",
                "Shamli",
                "Shravasti",
                "Siddharthnagar",
                "Sitapur",
                "Sonbhadra",
                "Sultanpur",
                "Unnao",
                "Varanasi"
            ), arrayOf(
                "Select District",
                "Araria",
                "Arwal",
                "Aurangabad",
                "Banka",
                "Begusarai",
                "Bhagalpur",
                "Bhojpur",
                "Buxar",
                "Darbhanga",
                "East Champaran",
                "Gaya",
                "Gopalganj",
                "Jamui",
                "Jehanabad",
                "Kaimur",
                "Katihar",
                "Khagaria",
                "Kishanganj",
                "Lakhisarai",
                "Madhepura",
                "Madhubani",
                "Munger",
                "Muzaffarpur",
                "Nalanda",
                "Nawada",
                "Patna",
                "Purnia",
                "Rohtas",
                "Saharsa",
                "Samastipur",
                "Saran",
                "Sheikhpura",
                "Sheohar",
                "Sitamarhi",
                "Siwan",
                "Supaul",
                "Vaishali",
                "West Champaran"
            ), arrayOf(
                "Select District",
                "East Sikkim",
                "North Sikkim",
                "South Sikkim",
                "West Sikkim"
            ), arrayOf(
                "Select District",
                "Tawang",
                "West Kameng",
                "East Kameng",
                "Papum Pare",
                "Kurung Kumey",
                "Kra Daadi",
                "Lower Subansiri",
                "Upper Subansiri",
                "West Siang",
                "Kamle",
                "Lepa Rada",
                "Pakke Kessang",
                "Shi Yomi",
                "East Siang",
                "Siang",
                "Upper Siang",
                "Lower Siang",
                "Lower Dibang Valley",
                "Dibang Valley",
                "Anjaw",
                "Lohit",
                "Namsai",
                "Changlang",
                "Tirap",
                "Longding"
            ), arrayOf(
                "Select District",
                "Dimapur",
                "Kiphire",
                "Kohima",
                "Longleng",
                "Mokokchung",
                "Noklak",
                "Mon",
                "Peren",
                "Phek",
                "Tuensang",
                "Wokha",
                "Zunheboto"
            ), arrayOf(
                "Select District",
                "Bishnupur",
                "Chandel",
                "Churachandpur",
                "Imphal East",
                "Imphal West",
                "Jiribam",
                "Kakching",
                "Kamjong",
                "Kangpokpi",
                "Noney",
                "Pherzawl",
                "Senapati",
                "Tamenglong",
                "Tengnoupal",
                "Thoubal",
                "Ukhrul"
            ),arrayOf(
                "Select District",
                "Aizawl",
                "Champhai",
                "Kolasib",
                "Lawngtlai",
                "Lunglei",
                "Mamit",
                "Saiha",
                "Serchhip"
            ), arrayOf(
                "Select District",
                "Dhalai",
                "Gomati",
                "Khowai",
                "North Tripura",
                "Sepahijala",
                "South Tripura",
                "Unakoti",
                "West Tripura"
            ), arrayOf(
                "Select District",
                "East Garo Hills",
                "East Jaintia Hills",
                "East Khasi Hills",
                "North Garo Hills",
                "Ri Bhoi",
                "South Garo Hills",
                "South West Garo Hills ",
                "South West Khasi Hills",
                "West Garo Hills",
                "West Jaintia Hills",
                "West Khasi Hills"
            ),arrayOf(
                "Select District",
                "Baksa",
                "Barpeta",
                "Biswanath",
                "Bongaigaon",
                "Cachar",
                "Charaideo",
                "Chirang",
                "Darrang",
                "Dhemaji",
                "Dhubri",
                "Dibrugarh",
                "Goalpara",
                "Golaghat",
                "Hailakandi",
                "Hojai",
                "Jorhat",
                "Kamrup Metropolitan",
                "Kamrup",
                "Karbi Anglong",
                "Karimganj",
                "Kokrajhar",
                "Lakhimpur",
                "Majuli",
                "Morigaon",
                "Nagaon",
                "Nalbari",
                "Dima Hasao",
                "Sivasagar",
                "Sonitpur",
                "South Salmara-Mankachar",
                "Tinsukia",
                "Udalguri",
                "West Karbi Anglong"
            ), arrayOf(
                "Select District",
                "Alipurduar",
                "Bankura",
                "Birbhum",
                "Cooch Behar",
                "Dakshin Dinajpur",
                "Darjeeling",
                "Hooghly",
                "Howrah",
                "Jalpaiguri",
                "Jhargram",
                "Kalimpong",
                "Kolkata",
                "Malda",
                "Murshidabad",
                "Nadia",
                "North 24 Parganas",
                "Paschim Bardhaman",
                "Paschim Medinipur",
                "Purba Bardhaman",
                "Purba Medinipur",
                "Purulia",
                "South 24 Parganas",
                "Uttar Dinajpur"
            ), arrayOf(
                "Select District",
                "Bokaro",
                "Chatra",
                "Deoghar",
                "Dhanbad",
                "Dumka",
                "East Singhbhum",
                "Garhwa",
                "Giridih",
                "Godda",
                "Gumla",
                "Hazaribag",
                "Jamtara",
                "Khunti",
                "Koderma",
                "Latehar",
                "Lohardaga",
                "Pakur",
                "Palamu",
                "Ramgarh",
                "Ranchi",
                "Sahebganj",
                "Seraikela Kharsawan",
                "Simdega",
                "West Singhbhum"
            ),arrayOf(
                "Select District",
                "Angul",
                "Balangir",
                "Balasore",
                "Bargarh",
                "Bhadrak",
                "Boudh",
                "Cuttack",
                "Debagarh",
                "Dhenkanal",
                "Gajapati",
                "Ganjam",
                "Jagatsinghpur",
                "Jajpur",
                "Jharsuguda",
                "Kalahandi",
                "Kandhamal",
                "Kendrapara",
                "Kendujhar",
                "Khordha",
                "Koraput",
                "Malkangiri",
                "Mayurbhanj",
                "Nabarangpur",
                "Nayagarh",
                "Nuapada",
                "Puri",
                "Rayagada",
                "Sambalpur",
                "Subarnapur",
                "Sundergarh",
                "Khordha"
            ),arrayOf(
                "Select District",
                "Balod",
                "Baloda Bazar",
                "Balrampur Ramanujganj*",
                "Bastar",
                "Bemetara",
                "Bijapur",
                "Bilaspur",
                "Dantewada",
                "Dhamtari",
                "Durg",
                "Gariaband",
                "Janjgir-Champa",
                "Jashpur",
                "Kabirdham",
                "Kanker",
                "Kondagaon",
                "Korba",
                "Koriya",
                "Mahasamund",
                "Mungeli",
                "Narayanpur",
                "Raigarh",
                "Raipur",
                "Rajnandgaon",
                "Sukma",
                "Surajpur  ",
                "Surguja",
                "Balrampur Ramanujganj",
                "Gaurela Pendra Marwahi"
            ), arrayOf(
                "Select District",
                "Agar Malwa",
                "Alirajpur",
                "Anuppur",
                "Ashoknagar",
                "Balaghat",
                "Barwani",
                "Betul",
                "Bhind",
                "Bhopal",
                "Burhanpur",
                "Chhatarpur",
                "Chhindwara",
                "Damoh",
                "Datia",
                "Dewas",
                "Dhar",
                "Dindori",
                "Guna",
                "Gwalior",
                "Harda",
                "Hoshangabad",
                "Indore",
                "Jabalpur",
                "Jhabua",
                "Katni",
                "Khandwa",
                "Khargone",
                "Mandla",
                "Mandsaur",
                "Morena",
                "Narsinghpur",
                "Neemuch",
                "Panna",
                "Raisen",
                "Rajgarh",
                "Ratlam",
                "Rewa",
                "Sagar",
                "Satna",
                "Sehore",
                "Seoni",
                "Shahdol",
                "Shajapur",
                "Sheopur",
                "Shivpuri",
                "Sidhi",
                "Singrauli",
                "Tikamgarh",
                "Ujjain",
                "Umaria",
                "Vidisha",
                "Niwari"
            ), arrayOf(
                "Select District",
                "Ahmedabad",
                "Amreli",
                "Anand",
                "Aravalli",
                "Banaskantha",
                "Bharuch",
                "Bhavnagar",
                "Botad",
                "Chhota Udaipur",
                "Dahod",
                "Dang",
                "Devbhoomi Dwarka",
                "Gandhinagar",
                "Gir Somnath",
                "Jamnagar",
                "Junagadh",
                "Kutch",
                "Kheda",
                "Mahisagar",
                "Mehsana",
                "Morbi",
                "Narmada",
                "Navsari",
                "Panchmahal",
                "Patan",
                "Porbandar",
                "Rajkot",
                "Sabarkantha",
                "Surat",
                "Surendranagar",
                "Tapi",
                "Vadodara",
                "Valsad"
            ), arrayOf(
                "Select District",
                "Daman",
                "Diu"
            ),arrayOf(
                "Select District",
                "Dadra Nagar Haveli"
            ), arrayOf(
                "Select District",
                "Ahmednagar",
                "Akola",
                "Amravati",
                "Aurangabad",
                "Beed",
                "Bhandara",
                "Buldhana",
                "Chandrapur",
                "Dhule",
                "Gadchiroli",
                "Gondia",
                "Hingoli",
                "Jalgaon",
                "Jalna",
                "Kolhapur",
                "Latur",
                "Mumbai City",
                "Mumbai Suburban",
                "Nagpur",
                "Nanded",
                "Nandurbar",
                "Nashik",
                "Osmanabad",
                "Palghar",
                "Parbhani",
                "Pune",
                "Raigad",
                "Ratnagiri",
                "Sangli",
                "Satara",
                "Sindhudurg",
                "Solapur",
                "Thane",
                "Wardha",
                "Washim",
                "Yavatmal"
            ), arrayOf(
                "Select District",
                "Anantapur",
                "Chittoor",
                "East Godavari",
                "Guntur",
                "Kadapa",
                "Krishna",
                "Kurnool",
                "Nellore",
                "Prakasam",
                "Srikakulam",
                "Visakhapatnam",
                "Vizianagaram",
                "West Godavari"
            ), arrayOf(
                "Select District",
                "Bagalkot",
                "Bellary",
                "Belgaum",
                "Bangalore Rural",
                "Bangalore Urban",
                "Bidar",
                "Chamarajanagar",
                "Chikkaballapur",
                "Chikkamagaluru",
                "Chitradurga",
                "Dakshina Kannada",
                "Davanagere",
                "Dharwad",
                "Gadag",
                "Hassan",
                "Haveri",
                "Gulbarga",
                "Kodagu",
                "Kolar",
                "Koppal",
                "Mandya",
                "Mysore",
                "Raichur",
                "Ramanagara",
                "Shivmoga",
                "Tumkur",
                "Udupi",
                "Uttara Kannada",
                "Vijayapura",
                "Yadgir"
            ), arrayOf(
                "Select District",
                "North Goa",
                "South Goa"
            ), arrayOf(
                "Select District",
                "Lakshadweep"
            ), arrayOf(
                "Select District",
                "Alappuzha",
                "Ernakulam",
                "Idukki",
                "Kannur",
                "Kasaragod",
                "Kollam",
                "Kottayam",
                "Kozhikode",
                "Malappuram",
                "Palakkad",
                "Pathanamthitta",
                "Thiruvananthapuram",
                "Thrissur",
                "Wayanad"
            ), arrayOf(
                "Select District",
                "Ariyalur",
                "Chengalpattu",
                "Chennai",
                "Coimbatore",
                "Cuddalore",
                "Dharmapuri",
                "Dindigul",
                "Erode",
                "Kallakurichi",
                "Kanchipuram",
                "Kanyakumari",
                "Karur",
                "Krishnagiri",
                "Madurai",
                "Nagapattinam",
                "Namakkal",
                "Nilgiris",
                "Perambalur",
                "Pudukkottai",
                "Ramanathapuram",
                "Salem",
                "Sivaganga",
                "Tenkasi",
                "Thanjavur",
                "Theni",
                "Thoothukudi",
                "Tiruchirappalli",
                "Tirunelveli",
                "Tiruppur",
                "Tirupattur",
                "Tiruvallur",
                "Tiruvannamalai",
                "Tiruvarur",
                "Vellore",
                "Viluppuram",
                "Virudhunagar"
            ), arrayOf(
                "Select District",
                "Karaikal",
                "Mahe",
                "Puducherry",
                "Yanam"
            ), arrayOf(
                "Select District",
                "Nicobars",
                "North And Middle Andaman",
                "South Andaman"
            ), arrayOf(
                "Select District",
                "Adilabad",
                "Bhadradri Kothagudem",
                "Hyderabad",
                "Jagtial",
                "Jangaon",
                "Jayashankar Bhupalpally",
                "Jogulamba Gadwal",
                "Kamareddy",
                "Karimnagar",
                "Khammam",
                "Komaram Bheem",
                "Mahabubabad",
                "Mahabubnagar",
                "Mancherial",
                "Medak",
                "Medchal",
                "Nagarkurnool",
                "Nalgonda",
                "Nirmal",
                "Nizamabad",
                "Peddapalli",
                "Rajanna Sircilla",
                "Rangareddy",
                "Sangareddy",
                "Siddipet",
                "Suryapet",
                "Vikarabad",
                "Wanaparthy",
                "Warangal Rural",
                "Warangal Urban",
                "Yadadri Bhuvanagiri",
                "Mulugu",
                "Narayanpet"
            ), arrayOf(
                "Select District",
                "Kargil",
                "Leh"
            )
        )

    }
}